version: '3.6'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${msql_password}
      MYSQL_DATABASE: ${database}
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql

  web-php:
    build: ./php/
    container_name: web-php
    env_file:
      - web-php-variables.env
    ports:
      - "5000:80"
    volumes:
      - ./html:/var/www/html
